### ISSUE TITLE
Flipped vertical eye tracking axis in some games (unity?) + Foveation Options

### ISSUE THREAD

**Issue by ducko0** [mbucchia/PimaxMagic4All#1]
Noticed that the eye tracking seemed to be flipped in some unity games. (Using quest pro + VD)

I am not super experienced with coding, but I was able to fix it for myself by changing line 370 of dllmain.cpp like this:

> outInfo->GazeTan[i] = {gaze.x, -gaze.y-0.5f};
(a better solution might be to add some sort of toggle to the user interface for flipping the values)

---

Also, is there any way to adjust or see the actual level of foveation and width of the rings? Even on the maximum mode, the performance gain for me was not really as good as I would have expected and it appears that the width of the inner ring is much wider than it needs to be (looks like about 60-70% of the full fov).

Potentially the width of rings are bugged and seem to be wider at higher base resolutions, although I still need to test a bit more to determine if that's actually true.

**Comment by mbucchia** [comment]
Hey!

The code doing all the actual VRS (foveation) isn't mine, it's the Pimax (closed source) coee.

**Comment by mbucchia** [comment]
Hey!

The code doing all the actual VRS (foveation) isn't mine, it's the Pimax (closed source) code. I haven't found a way to control finely the settings other than the 3 presets.

For the Upside-down thing, it's a common thing Unity does. Your solution is fine, perhaps I just need to make a checkbox in the UI to do this. I don't think there is a way to auto-detect it, though perhaps I can look at the loaded dlls and unity often had recognizable ones. But the next problem is that not all Unity games do the Upside-down!!
