### ISSUE TITLE
EyeTrackVR support

### ISSUE THREAD

**Issue by 0Human0** [mbucchia/PimaxMagic4All#3]
There's this open-source program called EyeTrackVR that lets you build EyeTracking into any headset and it would be very nice if I could combine PimaxMagic4All with it. Here's the link to their documentation and GitHub https://docs.eyetrackvr.dev/

**Comment by mbucchia** [comment]
I gave them instructions on how to do it before and they actually got some code working in OpenXR-Eye-Trackers (which is the parent project of PimaxMagic4All providing the eye tracking data): https://github.com/mbucchia/OpenXR-Eye-Trackers/commit/88efbaab4631295f2caa4a8a04e0b64900d0c3b1

They never pursued as far as I can tell(?)

I have 0 interest in adding code myself for such a niche scenario.
