### ISSUE TITLE
SteamVr doesn’t work anymore

### ISSUE THREAD

**Issue by Day185** [mbucchia/PimaxMagic4All#4]
Hi! I installed your utility but now SteamVR doesn’t work anymore. It says that it blocked add-ons… how can i go back and remove totally PimaxMagic4All and all Pimax things?

**Comment by mbucchia** [comment]
This tool doesn't install anything permanent on your system that SteamVR uses. You can see the list of files copied in your windows\system32 folder: https://github.com/mbucchia/PimaxMagic4All/blob/main/install_system_files.bat and try deleting those 4 files. They are not used by SteamVR though, so I doubt they are the issue.

Try re-enabling the add-on for your headset in SteamVR Manage Add-ons.

**Comment by Day185** [comment]
Thanks for your answer… Vietual Desktop was blocked after the installation by steam VR and i didn’t have access to steam Vr settings… so i uninstalled everything reinstalled ans now it seems to work like before…
